var controllers=require('../Controller/controllers');
var driverControllers=require('../Controller/driverControllers');
var adminControllers=require('../Controller/adminControllers');

exports.plugin={
    register:(server,options,next)=>{

        server.route({
            method:'POST',
            path:'/user/signup',
            options:{
                handler:controllers.userSignUp,
            }
        }),
        server.route({
            method:'POST',
            path:'/user/signin',
            options:{
                 handler:controllers.userSignIn,
            }
        }),
        server.route({
            method:'POST',
            path:'/user/createBooking',
            options:{
                 handler:controllers.userCreateBooking
            }
        }),
        server.route({
            method:'GET',
            path:'/user/getBookings',
            options:{
                handler:controllers.userGetBookings,
            }
        }),
        server.route({
            method:'GET',
            path:'/user/getBooking/{user_id}',
            options:{
                 handler:controllers.userGetBookingWithId
            }
        }),
        server.route({
            method:'GET',
            path:'/user/getBooking/{from_date}/{to_date}',
            options:{
                 handler:controllers.userBookingWithFilteredDate
            }
        }),
        server.route({
            method:'POST',
            path:'/driver/signup',
            options:{
                 handler:driverControllers.driverSignUp
            }
        }),
        server.route({
            method:'POST',
            path:'/driver/signin',
            options:{
                  handler:driverControllers.driverSignIn
            }
        }),
        server.route({
            method:'POST',
            path:'/driver/confirmOrRejectBooking',
            options:{
                  handler:driverControllers.driverConfirmRejectBookings
            }
        }),
        server.route({
            method:'GET',
            path:'/admin/getBookings',
            options:{
                handler:adminControllers.adminGetBookings
            }
        }),
        server.route({
            method:'GET',
            path:'/admin/getBookings/{user_id}',
            options:{
                 handler:adminControllers.adminGetBookingsWithUserId
            }
        }),
        server.route({
            method:'GET',
            path:'/admin/getBookings/{from_date}/{to_date}',
            options:{
                   handler:adminControllers.adminGetBookingsWithDateFilter
            }
        }),
        server.route({
            method:'GET',
            path:'/admin/freeDrivers',
            options:{
                    handler:adminControllers.getFreeDrivers
            }
        }),
        server.route({
            method:'PUT',
            path:'/admin/assignDrivers/{booking_id}',
            options:{
                    handler:adminControllers.assignDrivers
            }
        })

    },
    name:'api',
    version:'1.0.0'

}