var controllers=require('../Controller/controllers');
var driverControllers=require('../Controller/driverControllers');
var adminControllers=require('../Controller/adminControllers');

var routes=[
    {
        method:'POST',
        path:'/user/signup',
        options:{
            handler:controllers.userSignUp,
        }
    },
    {
        method:'POST',
        path:'/user/signin',
        options:{
             handler:controllers.userSignIn,
        }
    },
    {
        method:'POST',
        path:'/user/createBooking',
        options:{
             handler:controllers.userCreateBooking
        }
    },
    {
        method:'GET',
        path:'/user/getBookings',
        options:{
            handler:controllers.userGetBookings,
        }
    },
    {
        method:'GET',
        path:'/user/getBooking/{user_id}',
        options:{
             handler:controllers.userGetBookingWithId
        }
    },
    {
        method:'GET',
        path:'/user/getBooking/{from_date}/{to_date}',
        options:{
             handler:controllers.userBookingWithFilteredDate
        }
    },
    {
        method:'POST',
        path:'/driver/signup',
        options:{
             handler:driverControllers.driverSignUp
        }
    },
    {
        method:'POST',
        path:'/driver/signin',
        options:{
              handler:driverControllers.driverSignIn
        }
    },
    {
        method:'POST',
        path:'/driver/confirmOrRejectBooking',
        options:{
              handler:driverControllers.driverConfirmRejectBookings
        }
    },
    {
        method:'GET',
        path:'/admin/getBookings',
        options:{
            handler:adminControllers.adminGetBookings
        }
    },
    {
        method:'GET',
        path:'/admin/getBookings/{user_id}',
        options:{
             handler:adminControllers.adminGetBookingsWithUserId
        }
    },
    {
        method:'GET',
        path:'/admin/getBookings/{from_date}/{to_date}',
        options:{
               handler:adminControllers.adminGetBookingsWithDateFilter
        }
    },
    {
        method:'GET',
        path:'/admin/freeDrivers',
        options:{
                handler:adminControllers.getFreeDrivers
        }
    },
    {
        method:'PUT',
        path:'/admin/assignDrivers/{booking_id}',
        options:{
                handler:adminControllers.assignDrivers
        }
    }
]

module.exports=routes;